// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/sMARCHz/secretaria-bot/internal/core/domain"
	"github.com/sMARCHz/secretaria-bot/internal/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFinanceServiceClient creates a new instance of MockFinanceServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinanceServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinanceServiceClient {
	mock := &MockFinanceServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFinanceServiceClient is an autogenerated mock type for the FinanceServiceClient type
type MockFinanceServiceClient struct {
	mock.Mock
}

type MockFinanceServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinanceServiceClient) EXPECT() *MockFinanceServiceClient_Expecter {
	return &MockFinanceServiceClient_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function for the type MockFinanceServiceClient
func (_mock *MockFinanceServiceClient) Deposit(transactionRequest *domain.TransactionRequest) (*domain.TransactionResponse, *errors.AppError) {
	ret := _mock.Called(transactionRequest)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 *domain.TransactionResponse
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func(*domain.TransactionRequest) (*domain.TransactionResponse, *errors.AppError)); ok {
		return returnFunc(transactionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.TransactionRequest) *domain.TransactionResponse); ok {
		r0 = returnFunc(transactionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.TransactionRequest) *errors.AppError); ok {
		r1 = returnFunc(transactionRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockFinanceServiceClient_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockFinanceServiceClient_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - transactionRequest *domain.TransactionRequest
func (_e *MockFinanceServiceClient_Expecter) Deposit(transactionRequest interface{}) *MockFinanceServiceClient_Deposit_Call {
	return &MockFinanceServiceClient_Deposit_Call{Call: _e.mock.On("Deposit", transactionRequest)}
}

func (_c *MockFinanceServiceClient_Deposit_Call) Run(run func(transactionRequest *domain.TransactionRequest)) *MockFinanceServiceClient_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.TransactionRequest
		if args[0] != nil {
			arg0 = args[0].(*domain.TransactionRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFinanceServiceClient_Deposit_Call) Return(transactionResponse *domain.TransactionResponse, appError *errors.AppError) *MockFinanceServiceClient_Deposit_Call {
	_c.Call.Return(transactionResponse, appError)
	return _c
}

func (_c *MockFinanceServiceClient_Deposit_Call) RunAndReturn(run func(transactionRequest *domain.TransactionRequest) (*domain.TransactionResponse, *errors.AppError)) *MockFinanceServiceClient_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockFinanceServiceClient
func (_mock *MockFinanceServiceClient) GetBalance() (*domain.GetBalanceResponse, *errors.AppError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *domain.GetBalanceResponse
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func() (*domain.GetBalanceResponse, *errors.AppError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *domain.GetBalanceResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetBalanceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *errors.AppError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockFinanceServiceClient_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockFinanceServiceClient_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
func (_e *MockFinanceServiceClient_Expecter) GetBalance() *MockFinanceServiceClient_GetBalance_Call {
	return &MockFinanceServiceClient_GetBalance_Call{Call: _e.mock.On("GetBalance")}
}

func (_c *MockFinanceServiceClient_GetBalance_Call) Run(run func()) *MockFinanceServiceClient_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFinanceServiceClient_GetBalance_Call) Return(getBalanceResponse *domain.GetBalanceResponse, appError *errors.AppError) *MockFinanceServiceClient_GetBalance_Call {
	_c.Call.Return(getBalanceResponse, appError)
	return _c
}

func (_c *MockFinanceServiceClient_GetBalance_Call) RunAndReturn(run func() (*domain.GetBalanceResponse, *errors.AppError)) *MockFinanceServiceClient_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverviewAnnualStatement provides a mock function for the type MockFinanceServiceClient
func (_mock *MockFinanceServiceClient) GetOverviewAnnualStatement() (*domain.GetOverviewStatementResponse, *errors.AppError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOverviewAnnualStatement")
	}

	var r0 *domain.GetOverviewStatementResponse
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func() (*domain.GetOverviewStatementResponse, *errors.AppError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *domain.GetOverviewStatementResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetOverviewStatementResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *errors.AppError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockFinanceServiceClient_GetOverviewAnnualStatement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverviewAnnualStatement'
type MockFinanceServiceClient_GetOverviewAnnualStatement_Call struct {
	*mock.Call
}

// GetOverviewAnnualStatement is a helper method to define mock.On call
func (_e *MockFinanceServiceClient_Expecter) GetOverviewAnnualStatement() *MockFinanceServiceClient_GetOverviewAnnualStatement_Call {
	return &MockFinanceServiceClient_GetOverviewAnnualStatement_Call{Call: _e.mock.On("GetOverviewAnnualStatement")}
}

func (_c *MockFinanceServiceClient_GetOverviewAnnualStatement_Call) Run(run func()) *MockFinanceServiceClient_GetOverviewAnnualStatement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFinanceServiceClient_GetOverviewAnnualStatement_Call) Return(getOverviewStatementResponse *domain.GetOverviewStatementResponse, appError *errors.AppError) *MockFinanceServiceClient_GetOverviewAnnualStatement_Call {
	_c.Call.Return(getOverviewStatementResponse, appError)
	return _c
}

func (_c *MockFinanceServiceClient_GetOverviewAnnualStatement_Call) RunAndReturn(run func() (*domain.GetOverviewStatementResponse, *errors.AppError)) *MockFinanceServiceClient_GetOverviewAnnualStatement_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverviewMonthlyStatement provides a mock function for the type MockFinanceServiceClient
func (_mock *MockFinanceServiceClient) GetOverviewMonthlyStatement() (*domain.GetOverviewStatementResponse, *errors.AppError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOverviewMonthlyStatement")
	}

	var r0 *domain.GetOverviewStatementResponse
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func() (*domain.GetOverviewStatementResponse, *errors.AppError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *domain.GetOverviewStatementResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetOverviewStatementResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *errors.AppError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockFinanceServiceClient_GetOverviewMonthlyStatement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverviewMonthlyStatement'
type MockFinanceServiceClient_GetOverviewMonthlyStatement_Call struct {
	*mock.Call
}

// GetOverviewMonthlyStatement is a helper method to define mock.On call
func (_e *MockFinanceServiceClient_Expecter) GetOverviewMonthlyStatement() *MockFinanceServiceClient_GetOverviewMonthlyStatement_Call {
	return &MockFinanceServiceClient_GetOverviewMonthlyStatement_Call{Call: _e.mock.On("GetOverviewMonthlyStatement")}
}

func (_c *MockFinanceServiceClient_GetOverviewMonthlyStatement_Call) Run(run func()) *MockFinanceServiceClient_GetOverviewMonthlyStatement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFinanceServiceClient_GetOverviewMonthlyStatement_Call) Return(getOverviewStatementResponse *domain.GetOverviewStatementResponse, appError *errors.AppError) *MockFinanceServiceClient_GetOverviewMonthlyStatement_Call {
	_c.Call.Return(getOverviewStatementResponse, appError)
	return _c
}

func (_c *MockFinanceServiceClient_GetOverviewMonthlyStatement_Call) RunAndReturn(run func() (*domain.GetOverviewStatementResponse, *errors.AppError)) *MockFinanceServiceClient_GetOverviewMonthlyStatement_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverviewStatement provides a mock function for the type MockFinanceServiceClient
func (_mock *MockFinanceServiceClient) GetOverviewStatement(getOverviewStatementRequest *domain.GetOverviewStatementRequest) (*domain.GetOverviewStatementResponse, *errors.AppError) {
	ret := _mock.Called(getOverviewStatementRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetOverviewStatement")
	}

	var r0 *domain.GetOverviewStatementResponse
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func(*domain.GetOverviewStatementRequest) (*domain.GetOverviewStatementResponse, *errors.AppError)); ok {
		return returnFunc(getOverviewStatementRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.GetOverviewStatementRequest) *domain.GetOverviewStatementResponse); ok {
		r0 = returnFunc(getOverviewStatementRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetOverviewStatementResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.GetOverviewStatementRequest) *errors.AppError); ok {
		r1 = returnFunc(getOverviewStatementRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockFinanceServiceClient_GetOverviewStatement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverviewStatement'
type MockFinanceServiceClient_GetOverviewStatement_Call struct {
	*mock.Call
}

// GetOverviewStatement is a helper method to define mock.On call
//   - getOverviewStatementRequest *domain.GetOverviewStatementRequest
func (_e *MockFinanceServiceClient_Expecter) GetOverviewStatement(getOverviewStatementRequest interface{}) *MockFinanceServiceClient_GetOverviewStatement_Call {
	return &MockFinanceServiceClient_GetOverviewStatement_Call{Call: _e.mock.On("GetOverviewStatement", getOverviewStatementRequest)}
}

func (_c *MockFinanceServiceClient_GetOverviewStatement_Call) Run(run func(getOverviewStatementRequest *domain.GetOverviewStatementRequest)) *MockFinanceServiceClient_GetOverviewStatement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.GetOverviewStatementRequest
		if args[0] != nil {
			arg0 = args[0].(*domain.GetOverviewStatementRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFinanceServiceClient_GetOverviewStatement_Call) Return(getOverviewStatementResponse *domain.GetOverviewStatementResponse, appError *errors.AppError) *MockFinanceServiceClient_GetOverviewStatement_Call {
	_c.Call.Return(getOverviewStatementResponse, appError)
	return _c
}

func (_c *MockFinanceServiceClient_GetOverviewStatement_Call) RunAndReturn(run func(getOverviewStatementRequest *domain.GetOverviewStatementRequest) (*domain.GetOverviewStatementResponse, *errors.AppError)) *MockFinanceServiceClient_GetOverviewStatement_Call {
	_c.Call.Return(run)
	return _c
}

// Transfer provides a mock function for the type MockFinanceServiceClient
func (_mock *MockFinanceServiceClient) Transfer(transferRequest *domain.TransferRequest) (*domain.TransferResponse, *errors.AppError) {
	ret := _mock.Called(transferRequest)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 *domain.TransferResponse
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func(*domain.TransferRequest) (*domain.TransferResponse, *errors.AppError)); ok {
		return returnFunc(transferRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.TransferRequest) *domain.TransferResponse); ok {
		r0 = returnFunc(transferRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransferResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.TransferRequest) *errors.AppError); ok {
		r1 = returnFunc(transferRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockFinanceServiceClient_Transfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transfer'
type MockFinanceServiceClient_Transfer_Call struct {
	*mock.Call
}

// Transfer is a helper method to define mock.On call
//   - transferRequest *domain.TransferRequest
func (_e *MockFinanceServiceClient_Expecter) Transfer(transferRequest interface{}) *MockFinanceServiceClient_Transfer_Call {
	return &MockFinanceServiceClient_Transfer_Call{Call: _e.mock.On("Transfer", transferRequest)}
}

func (_c *MockFinanceServiceClient_Transfer_Call) Run(run func(transferRequest *domain.TransferRequest)) *MockFinanceServiceClient_Transfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.TransferRequest
		if args[0] != nil {
			arg0 = args[0].(*domain.TransferRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFinanceServiceClient_Transfer_Call) Return(transferResponse *domain.TransferResponse, appError *errors.AppError) *MockFinanceServiceClient_Transfer_Call {
	_c.Call.Return(transferResponse, appError)
	return _c
}

func (_c *MockFinanceServiceClient_Transfer_Call) RunAndReturn(run func(transferRequest *domain.TransferRequest) (*domain.TransferResponse, *errors.AppError)) *MockFinanceServiceClient_Transfer_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockFinanceServiceClient
func (_mock *MockFinanceServiceClient) Withdraw(transactionRequest *domain.TransactionRequest) (*domain.TransactionResponse, *errors.AppError) {
	ret := _mock.Called(transactionRequest)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 *domain.TransactionResponse
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func(*domain.TransactionRequest) (*domain.TransactionResponse, *errors.AppError)); ok {
		return returnFunc(transactionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.TransactionRequest) *domain.TransactionResponse); ok {
		r0 = returnFunc(transactionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.TransactionRequest) *errors.AppError); ok {
		r1 = returnFunc(transactionRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockFinanceServiceClient_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockFinanceServiceClient_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - transactionRequest *domain.TransactionRequest
func (_e *MockFinanceServiceClient_Expecter) Withdraw(transactionRequest interface{}) *MockFinanceServiceClient_Withdraw_Call {
	return &MockFinanceServiceClient_Withdraw_Call{Call: _e.mock.On("Withdraw", transactionRequest)}
}

func (_c *MockFinanceServiceClient_Withdraw_Call) Run(run func(transactionRequest *domain.TransactionRequest)) *MockFinanceServiceClient_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.TransactionRequest
		if args[0] != nil {
			arg0 = args[0].(*domain.TransactionRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFinanceServiceClient_Withdraw_Call) Return(transactionResponse *domain.TransactionResponse, appError *errors.AppError) *MockFinanceServiceClient_Withdraw_Call {
	_c.Call.Return(transactionResponse, appError)
	return _c
}

func (_c *MockFinanceServiceClient_Withdraw_Call) RunAndReturn(run func(transactionRequest *domain.TransactionRequest) (*domain.TransactionResponse, *errors.AppError)) *MockFinanceServiceClient_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
