// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/sMARCHz/secretaria-bot/internal/core/domain"
	"github.com/sMARCHz/secretaria-bot/internal/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBotService creates a new instance of MockBotService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBotService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBotService {
	mock := &MockBotService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBotService is an autogenerated mock type for the BotService type
type MockBotService struct {
	mock.Mock
}

type MockBotService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBotService) EXPECT() *MockBotService_Expecter {
	return &MockBotService_Expecter{mock: &_m.Mock}
}

// HandleTextMessage provides a mock function for the type MockBotService
func (_mock *MockBotService) HandleTextMessage(s string) (*domain.TextMessageResponse, *errors.AppError) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for HandleTextMessage")
	}

	var r0 *domain.TextMessageResponse
	var r1 *errors.AppError
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.TextMessageResponse, *errors.AppError)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.TextMessageResponse); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TextMessageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *errors.AppError); ok {
		r1 = returnFunc(s)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.AppError)
		}
	}
	return r0, r1
}

// MockBotService_HandleTextMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleTextMessage'
type MockBotService_HandleTextMessage_Call struct {
	*mock.Call
}

// HandleTextMessage is a helper method to define mock.On call
//   - s string
func (_e *MockBotService_Expecter) HandleTextMessage(s interface{}) *MockBotService_HandleTextMessage_Call {
	return &MockBotService_HandleTextMessage_Call{Call: _e.mock.On("HandleTextMessage", s)}
}

func (_c *MockBotService_HandleTextMessage_Call) Run(run func(s string)) *MockBotService_HandleTextMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBotService_HandleTextMessage_Call) Return(textMessageResponse *domain.TextMessageResponse, appError *errors.AppError) *MockBotService_HandleTextMessage_Call {
	_c.Call.Return(textMessageResponse, appError)
	return _c
}

func (_c *MockBotService_HandleTextMessage_Call) RunAndReturn(run func(s string) (*domain.TextMessageResponse, *errors.AppError)) *MockBotService_HandleTextMessage_Call {
	_c.Call.Return(run)
	return _c
}
