// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sMARCHz/secretaria-bot/internal/adapters/client/finance/pb"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockGRPCFinanceServiceClient creates a new instance of MockGRPCFinanceServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGRPCFinanceServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGRPCFinanceServiceClient {
	mock := &MockGRPCFinanceServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGRPCFinanceServiceClient is an autogenerated mock type for the FinanceServiceClient type
type MockGRPCFinanceServiceClient struct {
	mock.Mock
}

type MockGRPCFinanceServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGRPCFinanceServiceClient) EXPECT() *MockGRPCFinanceServiceClient_Expecter {
	return &MockGRPCFinanceServiceClient_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function for the type MockGRPCFinanceServiceClient
func (_mock *MockGRPCFinanceServiceClient) Deposit(ctx context.Context, in *pb.TransactionRequest, opts ...grpc.CallOption) (*pb.TransactionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 *pb.TransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.TransactionRequest, ...grpc.CallOption) (*pb.TransactionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.TransactionRequest, ...grpc.CallOption) *pb.TransactionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.TransactionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCFinanceServiceClient_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type MockGRPCFinanceServiceClient_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pb.TransactionRequest
//   - opts ...grpc.CallOption
func (_e *MockGRPCFinanceServiceClient_Expecter) Deposit(ctx interface{}, in interface{}, opts ...interface{}) *MockGRPCFinanceServiceClient_Deposit_Call {
	return &MockGRPCFinanceServiceClient_Deposit_Call{Call: _e.mock.On("Deposit",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGRPCFinanceServiceClient_Deposit_Call) Run(run func(ctx context.Context, in *pb.TransactionRequest, opts ...grpc.CallOption)) *MockGRPCFinanceServiceClient_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pb.TransactionRequest
		if args[1] != nil {
			arg1 = args[1].(*pb.TransactionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGRPCFinanceServiceClient_Deposit_Call) Return(transactionResponse *pb.TransactionResponse, err error) *MockGRPCFinanceServiceClient_Deposit_Call {
	_c.Call.Return(transactionResponse, err)
	return _c
}

func (_c *MockGRPCFinanceServiceClient_Deposit_Call) RunAndReturn(run func(ctx context.Context, in *pb.TransactionRequest, opts ...grpc.CallOption) (*pb.TransactionResponse, error)) *MockGRPCFinanceServiceClient_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockGRPCFinanceServiceClient
func (_mock *MockGRPCFinanceServiceClient) GetBalance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.GetBalanceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *pb.GetBalanceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*pb.GetBalanceResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *pb.GetBalanceResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetBalanceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCFinanceServiceClient_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockGRPCFinanceServiceClient_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockGRPCFinanceServiceClient_Expecter) GetBalance(ctx interface{}, in interface{}, opts ...interface{}) *MockGRPCFinanceServiceClient_GetBalance_Call {
	return &MockGRPCFinanceServiceClient_GetBalance_Call{Call: _e.mock.On("GetBalance",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGRPCFinanceServiceClient_GetBalance_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockGRPCFinanceServiceClient_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *emptypb.Empty
		if args[1] != nil {
			arg1 = args[1].(*emptypb.Empty)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGRPCFinanceServiceClient_GetBalance_Call) Return(getBalanceResponse *pb.GetBalanceResponse, err error) *MockGRPCFinanceServiceClient_GetBalance_Call {
	_c.Call.Return(getBalanceResponse, err)
	return _c
}

func (_c *MockGRPCFinanceServiceClient_GetBalance_Call) RunAndReturn(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.GetBalanceResponse, error)) *MockGRPCFinanceServiceClient_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverviewAnnualStatement provides a mock function for the type MockGRPCFinanceServiceClient
func (_mock *MockGRPCFinanceServiceClient) GetOverviewAnnualStatement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.OverviewStatementResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetOverviewAnnualStatement")
	}

	var r0 *pb.OverviewStatementResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*pb.OverviewStatementResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *pb.OverviewStatementResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.OverviewStatementResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverviewAnnualStatement'
type MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call struct {
	*mock.Call
}

// GetOverviewAnnualStatement is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockGRPCFinanceServiceClient_Expecter) GetOverviewAnnualStatement(ctx interface{}, in interface{}, opts ...interface{}) *MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call {
	return &MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call{Call: _e.mock.On("GetOverviewAnnualStatement",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *emptypb.Empty
		if args[1] != nil {
			arg1 = args[1].(*emptypb.Empty)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call) Return(overviewStatementResponse *pb.OverviewStatementResponse, err error) *MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call {
	_c.Call.Return(overviewStatementResponse, err)
	return _c
}

func (_c *MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call) RunAndReturn(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.OverviewStatementResponse, error)) *MockGRPCFinanceServiceClient_GetOverviewAnnualStatement_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverviewMonthlyStatement provides a mock function for the type MockGRPCFinanceServiceClient
func (_mock *MockGRPCFinanceServiceClient) GetOverviewMonthlyStatement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.OverviewStatementResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetOverviewMonthlyStatement")
	}

	var r0 *pb.OverviewStatementResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*pb.OverviewStatementResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *pb.OverviewStatementResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.OverviewStatementResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverviewMonthlyStatement'
type MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call struct {
	*mock.Call
}

// GetOverviewMonthlyStatement is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockGRPCFinanceServiceClient_Expecter) GetOverviewMonthlyStatement(ctx interface{}, in interface{}, opts ...interface{}) *MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call {
	return &MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call{Call: _e.mock.On("GetOverviewMonthlyStatement",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *emptypb.Empty
		if args[1] != nil {
			arg1 = args[1].(*emptypb.Empty)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call) Return(overviewStatementResponse *pb.OverviewStatementResponse, err error) *MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call {
	_c.Call.Return(overviewStatementResponse, err)
	return _c
}

func (_c *MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call) RunAndReturn(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.OverviewStatementResponse, error)) *MockGRPCFinanceServiceClient_GetOverviewMonthlyStatement_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverviewStatement provides a mock function for the type MockGRPCFinanceServiceClient
func (_mock *MockGRPCFinanceServiceClient) GetOverviewStatement(ctx context.Context, in *pb.OverviewStatementRequest, opts ...grpc.CallOption) (*pb.OverviewStatementResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetOverviewStatement")
	}

	var r0 *pb.OverviewStatementResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.OverviewStatementRequest, ...grpc.CallOption) (*pb.OverviewStatementResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.OverviewStatementRequest, ...grpc.CallOption) *pb.OverviewStatementResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.OverviewStatementResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.OverviewStatementRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCFinanceServiceClient_GetOverviewStatement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverviewStatement'
type MockGRPCFinanceServiceClient_GetOverviewStatement_Call struct {
	*mock.Call
}

// GetOverviewStatement is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pb.OverviewStatementRequest
//   - opts ...grpc.CallOption
func (_e *MockGRPCFinanceServiceClient_Expecter) GetOverviewStatement(ctx interface{}, in interface{}, opts ...interface{}) *MockGRPCFinanceServiceClient_GetOverviewStatement_Call {
	return &MockGRPCFinanceServiceClient_GetOverviewStatement_Call{Call: _e.mock.On("GetOverviewStatement",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGRPCFinanceServiceClient_GetOverviewStatement_Call) Run(run func(ctx context.Context, in *pb.OverviewStatementRequest, opts ...grpc.CallOption)) *MockGRPCFinanceServiceClient_GetOverviewStatement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pb.OverviewStatementRequest
		if args[1] != nil {
			arg1 = args[1].(*pb.OverviewStatementRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGRPCFinanceServiceClient_GetOverviewStatement_Call) Return(overviewStatementResponse *pb.OverviewStatementResponse, err error) *MockGRPCFinanceServiceClient_GetOverviewStatement_Call {
	_c.Call.Return(overviewStatementResponse, err)
	return _c
}

func (_c *MockGRPCFinanceServiceClient_GetOverviewStatement_Call) RunAndReturn(run func(ctx context.Context, in *pb.OverviewStatementRequest, opts ...grpc.CallOption) (*pb.OverviewStatementResponse, error)) *MockGRPCFinanceServiceClient_GetOverviewStatement_Call {
	_c.Call.Return(run)
	return _c
}

// Transfer provides a mock function for the type MockGRPCFinanceServiceClient
func (_mock *MockGRPCFinanceServiceClient) Transfer(ctx context.Context, in *pb.TransferRequest, opts ...grpc.CallOption) (*pb.TransferResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 *pb.TransferResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.TransferRequest, ...grpc.CallOption) (*pb.TransferResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.TransferRequest, ...grpc.CallOption) *pb.TransferResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransferResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.TransferRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCFinanceServiceClient_Transfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transfer'
type MockGRPCFinanceServiceClient_Transfer_Call struct {
	*mock.Call
}

// Transfer is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pb.TransferRequest
//   - opts ...grpc.CallOption
func (_e *MockGRPCFinanceServiceClient_Expecter) Transfer(ctx interface{}, in interface{}, opts ...interface{}) *MockGRPCFinanceServiceClient_Transfer_Call {
	return &MockGRPCFinanceServiceClient_Transfer_Call{Call: _e.mock.On("Transfer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGRPCFinanceServiceClient_Transfer_Call) Run(run func(ctx context.Context, in *pb.TransferRequest, opts ...grpc.CallOption)) *MockGRPCFinanceServiceClient_Transfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pb.TransferRequest
		if args[1] != nil {
			arg1 = args[1].(*pb.TransferRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGRPCFinanceServiceClient_Transfer_Call) Return(transferResponse *pb.TransferResponse, err error) *MockGRPCFinanceServiceClient_Transfer_Call {
	_c.Call.Return(transferResponse, err)
	return _c
}

func (_c *MockGRPCFinanceServiceClient_Transfer_Call) RunAndReturn(run func(ctx context.Context, in *pb.TransferRequest, opts ...grpc.CallOption) (*pb.TransferResponse, error)) *MockGRPCFinanceServiceClient_Transfer_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockGRPCFinanceServiceClient
func (_mock *MockGRPCFinanceServiceClient) Withdraw(ctx context.Context, in *pb.TransactionRequest, opts ...grpc.CallOption) (*pb.TransactionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 *pb.TransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.TransactionRequest, ...grpc.CallOption) (*pb.TransactionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.TransactionRequest, ...grpc.CallOption) *pb.TransactionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.TransactionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGRPCFinanceServiceClient_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockGRPCFinanceServiceClient_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pb.TransactionRequest
//   - opts ...grpc.CallOption
func (_e *MockGRPCFinanceServiceClient_Expecter) Withdraw(ctx interface{}, in interface{}, opts ...interface{}) *MockGRPCFinanceServiceClient_Withdraw_Call {
	return &MockGRPCFinanceServiceClient_Withdraw_Call{Call: _e.mock.On("Withdraw",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGRPCFinanceServiceClient_Withdraw_Call) Run(run func(ctx context.Context, in *pb.TransactionRequest, opts ...grpc.CallOption)) *MockGRPCFinanceServiceClient_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pb.TransactionRequest
		if args[1] != nil {
			arg1 = args[1].(*pb.TransactionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGRPCFinanceServiceClient_Withdraw_Call) Return(transactionResponse *pb.TransactionResponse, err error) *MockGRPCFinanceServiceClient_Withdraw_Call {
	_c.Call.Return(transactionResponse, err)
	return _c
}

func (_c *MockGRPCFinanceServiceClient_Withdraw_Call) RunAndReturn(run func(ctx context.Context, in *pb.TransactionRequest, opts ...grpc.CallOption) (*pb.TransactionResponse, error)) *MockGRPCFinanceServiceClient_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
